version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   volumes:
  #    - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  #   restart: always
  #   ports:
  #     - '8080:80'
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: wordpress
  #     MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - "8080:80"     # change to whatever you want
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
    working_dir: /var/www/html
    volumes:
      # - ./media:/var/www/html/media       # still working on assigning custom upload folder
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
  db_data:
